language: ruby
rvm:
- 2.0
- 2.1
- 2.2
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
sudo: false
cache: bundler
services:
  - redis-server
